services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_PRIVATE_KEY_PATH: /app/.secrets/keys/app.key
      JWT_PUBLIC_KEY_PATH: /app/.secrets/keys/app.pub
      MINIO_OUTER_ENDPOINT: ${MINIO_OUTER_ENDPOINT}
      MINIO_INNER_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
    volumes:
      - backend-data:/app/.secrets/keys
    entrypoint: >
      /bin/sh -c '
        if [ ! -f "$${JWT_PRIVATE_KEY_PATH}" ] || [ ! -f "$${JWT_PUBLIC_KEY_PATH}" ]; then
          openssl genpkey -algorithm RSA -out "$${JWT_PRIVATE_KEY_PATH}" -pkeyopt rsa_keygen_bits:2048 &> /dev/null
          openssl rsa -pubout -in "$${JWT_PRIVATE_KEY_PATH}" -out "$${JWT_PUBLIC_KEY_PATH}" &> /dev/null
          echo "RSA Keys generated successfully"
        else
          echo "Pre-existing RSA keys loaded successfully."
        fi
        exec $0 "$@"
      '
    command: java -jar app.jar
    restart: unless-stopped
    networks:
      - carekonet

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - carekonet

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    entrypoint: >
      /bin/sh -c '
        isAlive() { curl -sf http://minio:9000/minio/health/live; }
        minio $0 "$@" --quiet & echo $! > /tmp/minio.pid
        until isAlive; do sleep 1; done
        echo "MinIO is ready. Proceeding with setup..."
        mc alias set myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY}
        mc mb myminio/${MINIO_BUCKET}/ --ignore-existing
        mc anonymous set public myminio/${MINIO_BUCKET}
        kill -s INT $(cat /tmp/minio.pid) && rm /tmp/minio.pid
        while isAlive; do sleep 0.1; done
        exec minio $0 "$@"
      '
    command: server /data
    restart: unless-stopped
    networks:
      - carekonet

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - carekonet

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    ports:
      - "9002:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
    restart: unless-stopped
    networks:
      - sonarnet

  sonarqube-db:
    image: postgres:latest
    container_name: sonarqube-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sonarnet

volumes:
  backend-data:
  postgres-data:
  minio-data:
  redis-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-db-data:

networks:
  carekonet:
    driver: bridge
  sonarnet:
    driver: bridge
