server:
  port: 8081
  forward-headers-strategy: framework
spring:
  application:
    name: carekobooks
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME:carekobooks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    validate-migration-naming: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  web:
    resources:
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  realm: ${KEYCLOAK_REALM:carekobooks}
  client-id: ${KEYCLOAK_CLIENT_ID:backend-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
minio:
  inner-endpoint: ${MINIO_INNER_ENDPOINT}
  outer-endpoint: ${MINIO_OUTER_ENDPOINT:${minio.inner-endpoint}}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET:images}
springdoc:
  swagger-ui:
    custom-css-path: /static/swagger-ui.css
    operations-sorter: method
    tags-sorter: alpha
