spring:
  application:
    name: carekobooks
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
security:
  jwt:
    key:
      private: classpath:app.key
      public: classpath:app.pub
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}