server:
  forward-headers-strategy: framework
spring:
  application:
    name: carekobooks
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: true
    validate-migration-naming: true
  cache:
    type: redis
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
security:
  jwt:
    key:
      private: classpath:app.key
      public: classpath:app.pub
    token:
      access:
        cookie-name: access_token
        expiry-in-seconds: 3600
      refresh:
        cookie-name: refresh_token
        expiry-in-seconds: 10800
    roles-claim-name: roles
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
minio:
  outer-endpoint: ${MINIO_OUTER_ENDPOINT:${minio.inner-endpoint}}
  inner-endpoint: ${MINIO_INNER_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
