spring:
  application:
    name: carekobooks
  datasource:
    url: jdbc:mysql://localhost:3306/carekobooks?useTimezone=true&serverTimezone=UTC
    username: joaopedro
    password: 123
  jpa:
    hibernate:
      ddl-auto: update # Temporário, será alterado para "none" em breve
    open-in-view: false
security:
  jwt:
    token:
      secret-key: NTNjcjM3
      expiration-time-in-ms: 3600000