spring:
  application:
    name: carekobooks
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Temporário, será alterado para "none" em breve
    open-in-view: false
security:
  jwt:
    token:
      secret-key: ${SECRET_KEY}
      expiration-time-in-ms: 3600000
minio:
  url: http://localhost:9000
  accessKey: 0F2qdlYIBkMIgBBVIU2J
  secretKey: DagfKSSRGZ5efmW8U8VNyMztdbZyOtqjvpFGrMe1
  bucket: development
  secure: false
