spring:
  application:
    name: carekobooks
  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?useTimezone=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Temporário, será alterado para "none" em breve
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY}
      expiration-time-in-ms: 3600000
minio:
  endpoint: ${MINIO_ENDPOINT}
  username: ${MINIO_USERNAME}
  password: ${MINIO_PASSWORD}
  bucket: ${MINIO_BUCKET}