spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:carekobooks-postgres}:${DB_PORT:5432}/${DB_NAME:carekobooks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:carekobooks-redis}
      port: ${REDIS_PORT:6379}
keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:carekobooks}
  client-id: ${KEYCLOAK_CLIENT_ID:backend-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
minio:
  inner-endpoint: ${MINIO_INNER_ENDPOINT:http://minio:9000}
  outer-endpoint: ${MINIO_OUTER_ENDPOINT:${minio.inner-endpoint}}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
