spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:carekobooks-postgres}:${DB_PORT:5432}/${DB_NAME:carekobooks}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:carekobooks-redis}
      port: ${REDIS_PORT:6379}
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
security:
  jwt:
    key:
      private: file:/app/.secrets/keys/app.key
      public: file:/app/.secrets/keys/app.pub
minio:
  inner-endpoint: ${MINIO_INNER_ENDPOINT:http://carekobooks-minio:9000}
  outer-endpoint: ${MINIO_OUTER_ENDPOINT:${minio.inner-endpoint}}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}
