services:
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    ports:
      - "9100:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
    restart: unless-stopped
    networks:
      - sonarnet

  sonarqube-db:
    image: postgres:17
    container_name: sonarqube-db
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - sonarnet

volumes:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-db-data:

networks:
  sonarnet:
