create table book_threads
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    description varchar(1000) not null,
    title       varchar(255)  not null,
    book_id     bigint        not null
        constraint fkqj7g5oo9fpa1ci1i8f5gfsmyq
            references books,
    user_id     bigint        not null
        constraint fkrars1ydwmee29m84uoipcms2m
            references users
);
