create table book_thread_replies
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    content    varchar(1000) not null,
    thread_id  bigint        not null
        constraint fkfhhp5osl566y7n85cafeyb2r0
            references book_threads,
    user_id    bigint        not null
        constraint fk9kndk9ml7t4m7pcck7bigarmr
            references users
);
