insert into book_genres (created_at, updated_at, description, display_name, name)
values
    (now(), now(), 'Narrativa que se concentra no relacionamento amoroso entre os protagonistas', 'Romance', 'romance'),
    (now(), now(), 'Forma literária que utiliza a linguagem poética e estética', 'Poesia', 'poesia'),
    (now(), now(), 'Obra que apresenta conflitos emocionais intensos', 'Drama', 'drama'),
    (now(), now(), 'História com eventos catastróficos e finais infelizes', 'Tragédia', 'tragedia'),
    (now(), now(), 'Obra com elementos humorísticos e final feliz', 'Comédia', 'comedia'),
    (now(), now(), 'Ficção com elementos científicos e tecnológicos avançados', 'Ficção Científica', 'ficcao_cientifica'),
    (now(), now(), 'Narrativa com elementos mágicos e sobrenaturais', 'Fantasia', 'fantasia'),
    (now(), now(), 'Obra que busca provocar medo no leitor', 'Terror', 'terror'),
    (now(), now(), 'História que mantém tensão e expectativa', 'Suspense', 'suspense'),
    (now(), now(), 'Narrativa centrada na solução de um crime', 'Mistério', 'misterio'),
    (now(), now(), 'História com viagens e eventos emocionantes', 'Aventura', 'aventura'),
    (now(), now(), 'Romance com elementos de investigação criminal', 'Romance Policial', 'romance_policial'),
    (now(), now(), 'Romance ambientado em período histórico', 'Romance Histórico', 'romance_historico'),
    (now(), now(), 'Romance ambientado em época específica do passado', 'Romance de Época', 'romance_epoca'),
    (now(), now(), 'Narrativa curta com moral didática', 'Fábula', 'fabula'),
    (now(), now(), 'Narrativa ficcional breve', 'Conto', 'conto'),
    (now(), now(), 'Registro de fatos do cotidiano', 'Crônica', 'cronica'),
    (now(), now(), 'Narrativa da vida de uma pessoa', 'Biografia', 'biografia'),
    (now(), now(), 'Biografia escrita pelo próprio autor', 'Autobiografia', 'autobiografia'),
    (now(), now(), 'Relato pessoal de experiências vividas', 'Memórias', 'memorias'),
    (now(), now(), 'Texto argumentativo sobre determinado tema', 'Ensaio', 'ensaio'),
    (now(), now(), 'Obra escrita em forma de cartas', 'Epistolar', 'epistolar'),
    (now(), now(), 'Registro pessoal de eventos e reflexões', 'Diário', 'diario'),
    (now(), now(), 'Representação de sociedade futura opressiva', 'Distopia', 'distopia'),
    (now(), now(), 'Representação de sociedade ideal perfeita', 'Utopia', 'utopia'),
    (now(), now(), 'Literatura destinada ao público infantil', 'Literatura Infantil', 'literatura_infantil'),
    (now(), now(), 'Literatura para adolescentes e jovens adultos', 'Literatura Juvenil', 'literatura_juvenil'),
    (now(), now(), 'Ficção leve sobre mulheres jovens urbanas', 'Chick Lit', 'chick_lit'),
    (now(), now(), 'Incorporação de elementos mágicos em realidade cotidiana', 'Realismo Mágico', 'realismo_magico');
