create table books
(
    id                   bigint generated by default as identity
        primary key,
    created_at           timestamp(6),
    updated_at           timestamp(6),
    author_name          varchar(255) not null,
    page_count           integer      not null,
    published_at         date,
    publisher_name       varchar(255) not null,
    review_average_score double precision,
    synopsis             varchar(1000),
    title                varchar(255) not null,
    user_average_score   double precision,
    image_id             bigint
        constraint fkoruls93mh4gd3910ua20do9v5
            references images
            on delete set null
);
