create table book_genres
(
    id           bigint generated by default as identity
        primary key,
    created_at   timestamp(6),
    updated_at   timestamp(6),
    description  varchar(255),
    display_name varchar(100) not null,
    name         varchar(50)  not null
        constraint uk5p799253r9ujypw5w514898xk
            unique
);

alter table book_genres
    owner to postgres;

create index idx_name
    on book_genres (name);
