create table book_activities
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    page_count integer,
    status     varchar(255) not null
        constraint book_activities_status_check
            check ((status)::text = ANY
                   ((ARRAY ['READING'::character varying, 'PLANS_TO_READ'::character varying, 'FINISHED'::character varying])::text[])),
    book_id    bigint       not null
        constraint fk57yqy32r7i4lo4eu2v9py9w0g
            references books,
    user_id    bigint       not null
        constraint fk3nc29041t9h0sbk8a6qs20bgc
            references users
);
