create table book_progresses
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6),
    updated_at  timestamp(6),
    is_favorite boolean      not null,
    page_count  integer,
    score       integer,
    status      varchar(255) not null
        constraint book_progresses_status_check
            check ((status)::text = ANY
                   ((ARRAY ['READING'::character varying, 'PLANS_TO_READ'::character varying, 'FINISHED'::character varying])::text[])),
    book_id     bigint       not null
        constraint fkgpqoo93k4sy2yinde2dg1usx9
            references books,
    user_id     bigint       not null
        constraint fkp1b68omb8sxbfapj60a40skuu
            references users
);
