create table book_reviews
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6),
    updated_at timestamp(6),
    content    varchar(5000) not null,
    score      integer       not null,
    title      varchar(255)  not null,
    book_id    bigint        not null
        constraint fkcm2shivx19spbg0flc47mcrs1
            references books,
    user_id    bigint        not null
        constraint fkon3wfhxgwpfu7kl1wu54mw78u
            references users
);
